
name: 'Git Actions Pintos'

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  threads:
    name: 'Fase: Threads'
    runs-on: 'ubuntu-latest'
    env:
      phase: 'threads'
    steps:
      - name: 'Clonando repositorio'
        uses: 'actions/checkout@v2'
      - name: Pintos Checker
        id: phase
        uses: gbenm/pintos-checker@v1
        with:
            phase: "${{ env.phase }}"
            root: "."
            utils_path: "u
